sonar.projectKey=krasnonos-viktoriia_Laboratorna6
sonar.organization=krasnonos-viktoriia

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
